name: Publish package

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com"
          scope: "@the-curve-consulting"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          HUSKY: 0

      - name: Build package
        run: yarn build

      - name: Publish package to GitHub Packages
        run: npm publish
        env:
          HUSKY: 0
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js for npmjs
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          scope: "@the-curve-consulting"

      - name: Publish package to npmjs
        run: npm publish --registry https://registry.npmjs.org --access public --provenance
        env:
          HUSKY: 0
